language: c
os: linux
dist: jammy

env:
  global:
    - CACHE_DIR=${TRAVIS_HOME}/cache
    - TMP_DIR=${TRAVIS_HOME}/tmp
    - VCPKG_DIR=${TMP_DIR}/vcpkg

stages:
 - buildWin
 
cache:
  timeout: 900
  directories:
    - $CACHE_DIR

jobs:
  include:
    # debug builds
    - &linux
      stage: build
      compiler: gcc
      arch: amd64
      addons:
       apt:
        packages:
         - libjansson-dev
         - check
         - libssl-dev
         - lcov
         - gnutls-dev
      script:
       - sudo pip install codecov
       - autoreconf -fi
       - ./configure --without-openssl
       - make check
       - make distclean
       - ./configure --enable-code-coverage
       - make check-code-coverage
      after_success:
        - codecov
# windows
    - &windows
      stage: buildWin
      name: windows, vs2022
      os: windows
      compiler: cl
      arch: amd64
      script:
#       - cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat'
        - if not exist "${CACHE_DIR}" mkdir "${CACHE_DIR}"
        - mkdir "${TMP_DIR}"
        - mkdir "${VCPKG_DIR}"
        - pushd .
        - choco install visualstudio2022community -y
        - which cl.exe
        - cd ${TMP_DIR}
        - git clone https://github.com/microsoft/vcpkg
        - cd ${VCPKG_DIR}
        - ./bootstrap-vcpkg.bat
        - ./vcpkg.exe version
        - export PATH=${PATH}:"${VCPKG_DIR}"
        - popd
#       - set
        - vcpkg.exe install --x-install-root=${CACHE_DIR}
        - cmake -DCMAKE_TOOLCHAIN_FILE="%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake"
        - cmake --build . --config RelWithDebInfo
        - ctest -C Debug -VV

